name: iOS Build and Test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build-and-test-framework:
    runs-on: macos-13

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set Xcode 15
        run: |
          sudo xcode-select -switch /Applications/Xcode_15.1.app

      - name: Swift Lint
        run: swiftlint --strict

      - name: Swift Format
        run: swiftformat .

      - name: Install dependencies
        run: |
          gem install xcpretty

      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild -workspace Pipeable.xcworkspace -scheme Pipeable \
                     -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
                     test | xcpretty

  build-and-test-sample-app:
    runs-on: macos-13

    # defaults:
    #   run:
    #     working-directory: Samples/PipeableSample

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set Xcode 15
        run: |
          sudo xcode-select -switch /Applications/Xcode_15.1.app

      - name: Swift Lint
        run: swiftlint --strict

      - name: Swift Format
        run: swiftformat .

      - name: Install dependencies
        run: |
          gem install xcpretty

      - name: Build
        run: |
          set -o pipefail
          xcodebuild -workspace Pipeable.xcworkspace -scheme PipeableSample \
                     -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
                     build | xcpretty

