name: iOS Build and Test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build-and-test-framework:
    runs-on: macos-12

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Swift Lint
        run: swiftlint --strict

      - name: Swift Format
        run: swiftformat .

      - name: Install dependencies
        run: |
          gem install xcpretty

      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild -scheme Pipeable \
                     -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.1' \
                     test | xcpretty

  build-and-test-sample-app:
    runs-on: macos-12

    defaults:
      run:
        working-directory: Samples/PipeableSample

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Swift Lint
        run: swiftlint --strict

      - name: Swift Format
        run: swiftformat .

      - name: Install dependencies
        run: |
          gem install xcpretty

      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild -scheme Pipeable \
                     -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.1' \
                     test | xcpretty

