name: iOS Build and Test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build-and-test:
    runs-on: macos-12

    steps:
      - name: Set Xcode 14
        run: |
          sudo xcode-select -switch /Applications/Xcode_14.1.app

      - name: checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          gem install xcpretty

      # - name: List available simulators
      #   run: xcrun simctl list devices available

      # - name: List destination
      #   run: xcodebuild -showdestinations -project Pipeable.xcodeproj -scheme Pipeable

      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild -project Pipeable.xcodeproj \
                     -scheme Pipeable \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' \
                     test | xcpretty

