name: iOS Build and Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v3


    - name: Install dependencies
      run: |
        gem install xcpretty

    - name: Build and Test
      run: |
        xcodebuild -workspace project.xcworkspace \
                   -scheme YourScheme \
                   -sdk iphonesimulator \
                   -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.1' \
                   clean build test | xcpretty

