name: iOS Build and Test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          gem install xcpretty


      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild -project "Pipeable.xcodeproj" \
                     -scheme Pipeable \
                     -sdk iphonesimulator \
                     clean test | xcpretty

